rules:
  - id: naming_convention_variable
    description: 変数名はcamelCaseで記述する必要があります。
    pattern: ^(?!([a-z][a-zA-Z0-9]*)$).+$
    replacement: ""
    severity: error
  - id: naming_convention_function
    description: 関数名はcamelCaseで記述する必要があります。
    pattern: ^(?!([a-z][a-zA-Z0-9]*)$).+$
    replacement: ""
    severity: error
  - id: naming_convention_class
    description: クラス名はPascalCaseで記述する必要があります。
    pattern: ^(?!([A-Z][a-zA-Z0-9]*)$).+$
    replacement: ""
    severity: error
  - id: indent_2_spaces
    description: インデントはスペース2つを使用する必要があります。
    pattern: ^( +(?!\n))+$
    replacement: "  "
    severity: error
  - id: semicolon_at_end_of_line
    description: 行末にはセミコロンを記述する必要があります。
    pattern: ^(.*[^;])$
    replacement: "$1;"
    severity: warning
  - id: jsdoc_comment_for_function
    description: 関数にはJSDoc形式でコメントを記述する必要があります。
    pattern: ^(function\s+([a-zA-Z0-9]*)\s*\((.*)\)\s*\{)$
    replacement: "/**\n * @param {$3} \n */\n$1"
    severity: warning
